---
# role: ansible-role-samba-member
# file: tasks/main.yml

- name: "Tasks for ansible-role-samba-member"
  block:

    - name: "Set os_family dependent variables"
      include_vars: '{{ ansible_os_family }}.yml'

    - name: "Set distribution dependent variables"
      include_vars: "{{ item }}"
      vars:
        params:
          files:
            - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
            - '{{ ansible_distribution }}.yml'
            - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
          paths:
            - 'vars'
          skip: true
      loop: "{{ query('first_found', params, errors='ignore') }}"

    - name: "Install packages for ansible-role-samba-member"
      package:
        name: "{{ samba_member_packages }}"
        state: present
  when: samba_member_role_enabled | bool
