---
# role: ansible-role-samba-member
# file: molecule/vbox/molecule.yml

dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
    type: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: alpine-samba-member
    box: "generic/alpine312"
    cpus: 2
    memory: 1024
  - name: amazon-samba-member
    box: "bento/amazonlinux-2"
    cpus: 2
    memory: 1024
  - name: arch-samba-member
    box: "archlinux/archlinux"
    cpus: 2
    memory: 1024
  - name: centos-samba-member
    box: "centos/8"
    cpus: 2
    memory: 1024
  - name: debian-samba-member
    box: "debian/bullseye64"
    cpus: 2
    memory: 1024
  - name: fedora-samba-member
    box: "fedora/33-cloud-base"
    cpus: 2
    memory: 1024
  - name: opensuse-samba-member
    box: "generic/opensuse15"
    cpus: 2
    memory: 1024
  - name: oracle-samba-member
    box: "generic/oracle8"
    cpus: 2
    memory: 1024
  - name: ubuntu-samba-member
    box: "ubuntu/focal64"
    cpus: 2
    memory: 1024
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        samba_member_role_enabled: true
verifier:
  name: ansible
